### ISSUE TITLE
Automatic vite port detection

### ISSUE THREAD

**Issue by meech-ward** [Hacksore/vite-plugin-caddy#3]
This is awesome. I would love if the Caddy file could just detect my app's port though. I don't know enough about Caddy and Vite plugins to have an answer that i'm confident in, but I got this working. What do you think?

```js
function viteCaddyTlsPlugin() {
  return {
    name: "vite:caddy-tls",
    async configureServer(server) { // use configureServer so we can't get the port

      console.log("starting caddy plugin...");
      validateCaddyIsInstalled();

      server.httpServer?.once('listening', () => {
        // get the vite port
        const port = server.config.server.port;
        console.log(`Vite is running on port ${port}`);

        // use this when spawning the caddy file
        const handle = spawn(`VITE_PORT=${port || 5173} caddy run --config "${cwd}/Caddyfile"`, {
          shell: true
        });
        //...
        // everything else is the same
      })
    }
  };
}
```

**Caddy File:**
```
myapp.localhost {
  tls internal
  log stdout
  reverse_proxy localhost:{$VITE_PORT}
}

test.localhost {
  tls internal
  log stdout
  reverse_proxy localhost:{$VITE_PORT}
}
```

**Comment by Hacksore** [comment]
So I've taken a shot of just ripping out the caddyfile, it removes complexity from the user. They don't need to know how the caddy DSL works, just a simple object to pass as input.

What are you thoughts on this? feature branch https://github.com/Hacksore/vite-plugin-caddy/tree/feat/use-caddy-json

```ts
import { defineConfig } from "vite";
import caddyTls from "../src/index.js";

const config = defineConfig({
  server: {
    port: 3000,
  },
  plugins: [
    caddyTls({
      domains: ["ligam.localhost", "ok.localhost"],
    })
  ]
});

export default config;
```

**Comment by Hacksore** [comment]
@meech-ward You also mentioned that supporting the caddyfile file would be good for advanced use cases and those who really need it.

The biggest blocker there is parsing the caddyfile, we need to build some kind of proper parser. 

I'd think the best way to progress here is ship the non-caddyfile approach and track caddyfile support in a separate issue.

```ts
// abstract DSL
caddyTls({
  domains: ["ligma.localhost", "ok.localhost"],
})

// caddyfile support
caddyTls({
  caddyfile: true
  // caddyfilePath: "/tmp" // optional path, default is next to the vite.conf.ts
})
```
